Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 40

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: predicate

Style/SymbolArray:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

AllCops:
  Exclude:
    - bin/*
    - config_parser.gemspec
    - Rakefile
